### ISSUE TITLE
The last feature of the vectorial input does not appear in the output. Always ignored!

### ISSUE THREAD

**Issue by WCMC-vblanque** [JakubCha/exactextract_qgis#13] opened 2024-04-10 20:13 UTC
The last feature of the vectorial input does not appear in the output. Always ignored!

**INPUT:  12 features with id=[1;12]**
![image](https://github.com/JakubCha/exactextract_qgis/assets/141819111/c7546a62-b230-4dbd-af07-7462c144bfd6)

**OUTPUT:  only 11 features with id=[1;11]**, feature with id=12 is ignored
![image](https://github.com/JakubCha/exactextract_qgis/assets/141819111/04bfa60f-b307-4cd7-903e-2699a6a415d5)

**Comment by JakubCha** [comment] 2024-04-11 05:03
Hi,
I think I fixed this issue in a few last code changes. Unfortunately, (py)QGIS is not consistent when it comes to dealing with the feature ID - geopackage layers use hidden feature ID always starting with 1, regardless of FID field; shapefile files use id/ID column and database (postgres) layers use id column that is assigned to layer as a primary key. I made a change that considers these rules when you use more than 1 subtask. 

Can you try to install and test the new [release](https://github.com/JakubCha/exactextract_qgis/releases/download/v0.42/zonal_exact-0.42.zip) I created a few minutes ago? 

If the problem persists I will need the vector and raster layers in the same format (if it's shapefile I need a shapefile, if it's geopackage I need geopackage, etc.) that you use so I can debug this problem.

**Comment by JakubCha** [comment] 2024-04-11 09:50
@WCMC-vblanque remember to update `exactextract` to newest version.
`pip uninstall exactextract`
and then
`pip install exactextract` should work since `exactextract` is on PyPi now.

**Comment by JakubCha** [comment] 2024-04-17 08:42
@WCMC-vblanque any update on that? Does the problem persist?

**Comment by JakubCha** [comment] 2024-04-19 06:31
Closing as a stale problem for now. If the problem is still there, please let me know - with data that gives error if possible.

**Closed as not planned by JakubCha** 2024-04-19 06:31 UTC
Labels: bug

**Comment by WCMC-vblanque** [comment] 2024-05-21 21:18
Hi JakubCha, I am sorry not answering before. I have not been notified of your messages. I will test the new version right now and let you know.

**Comment by JakubCha** [comment] 2024-05-21 22:15
Hi. If you want to try out the newest version please use the current repo state or file attached. It's also uploaded in QGIs plugins. It's just waiting for approval from staff.
[zonal_exact-0.5.zip](https://github.com/JakubCha/exactextract_qgis/files/15395895/zonal_exact-0.5.zip)

**Comment by WCMC-vblanque** [comment] 2024-05-21 22:17
Hi Jakub, thanks a lot. I will test it right now and let you know.

I have just git pull the last version but I don't know how to install without pip.

I have tried pip install .  but it does not work

**Comment by JakubCha** [comment] 2024-05-22 15:14
You just install python package (`exactexctract`) with pip as written [here](https://github.com/JakubCha/exactextract_qgis?tab=readme-ov-file#installation)
You can install plugin by using .zip of package or you can install now directly from qgis default plugin repository. It was approved today.
